add own class name hashing
DigitecGalaxus/next-yak pull request #220
Opened 2024-11-25 12:11 UTC by jantimon

This PR is a first draft for minified CSS class names in production by generating deterministic but unique class names directly in the SWC plugin

The change will:

- reduce the class name size in css file (upto 20% gzip file size savings)
- reduce the ssr html size (because the class names are also used there)
- reduce the js bundle size (because we can skip the mappings and the class names are also there)

The generated code from the SWC plugin changes from

```tsx
import styleYak from "./input.yak.module.css"; 
styled.button(styleYak.Button);

to the following:

```tsx
import "./input.yak.module.css";
styled.button("Button_m7uBBu");
```

The PR will only work for Next.js versions with a `postcss-modules-local-by-default` version 4.1 or newer 

Still todo:
[ ] Test if single line comments `//` work for postcss ignore markers
[ ] Update css-loader imports from cross-file selectors and mixins to use the new class naming scheme

2024-11-29 12:46 UTC, Mad-Kat requested changes

2024-11-29 12:46 UTC, Mad-Kat commented on packages/next-yak/loaders/css-loader.ts
> +    "/* cssmodules-pure-ignore */",
Can't we do this directly in the SWC plugin?

2024-11-29 12:46 UTC, Mad-Kat commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +    assert_eq!(convention.get_css_variable_name(""), "yoPBkbUB");
Would be nice to see what happens if the values will reach >16

2024-11-29 12:46 UTC, Mad-Kat commented on packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.tsx
> +*/ /*#__PURE__*/ keyframes("fadeIn");
Does this work when the keyframe is local to the module?

2024-11-29 14:04 UTC, Mad-Kat commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +fn minify_number(num: u32) -> String {
add specific tests

2024-11-29 14:11 UTC, Mad-Kat commented on packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.tsx
> +*/ /*#__PURE__*/ keyframes("fadeIn");
todo: add `:global()` to the keyframe name

2024-12-03 11:25 UTC, jantimon commented on packages/next-yak/loaders/css-loader.ts
> +    "/* cssmodules-pure-ignore */",
Unfortunately not as `*/` will end the outer comment

2024-12-03 21:21 UTC, jantimon commented on packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.tsx
> +*/ /*#__PURE__*/ keyframes("fadeIn");
fixed

2025-04-02 18:41 UTC, jantimon commented
This PR requires

next 15.3.0-canary.30 (for CI pipelines)
next 15.3.0 (for stable release)

2025-04-02 18:43 UTC, jantimon commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +fn minify_number(num: u32) -> String {
done

2025-04-03 09:27 UTC, chklauser commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +      let base = self
If, and only if, we are talking about a path in the developer's file system. If `self.file_name` is a "logical" path in a source file import statement, then I would stick with `String`.

2025-04-03 12:29 UTC, jantimon commented on packages/next-yak/loaders/css-loader.ts
> +    result = "/* cssmodules-pure-no-check */\n" + result;
unfortunately we can't place comments inside comments as `*/` would terminate the generated css comment by the swc plugin

2025-04-03 12:54 UTC, jantimon commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +      let base = self
I didn't choose `path` because I believe it is a normalized path (always unix) and therefore might not work well with Path on windows

2025-04-03 14:13 UTC, Mad-Kat commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +      let base = self
They [fixed it for the absolut path](https://github.com/rust-lang/rust/issues/92750), but as we're only interested in [the stem](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem) I don't think this should be a problem

2025-04-03 14:18 UTC, jantimon commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +      let base = self
we need also to strip the path e.g. `/foo/bar.tsx` -> `bar` and this might be broken for windows

2025-04-03 14:46 UTC, jantimon commented on packages/yak-swc/yak_swc/src/naming_convention.rs
> +      let base = self
I changed it to `use std::path::Path;` 👍

2025-04-04 05:57 UTC, merged